import type { ThemeDefinition } from '@/types';

export const themes: Record<string, ThemeDefinition> = {
  basic: {
    id: 'basic',
    name: '기본',
    nameEn: 'Basic',
    description: '깔끔하고 범용적인 기본 테마',
    cssVariables: {
      '--color-primary': '59 130 246',
      '--color-primary-light': '96 165 250',
      '--color-primary-dark': '37 99 235',
      '--color-secondary': '100 116 139',
      '--color-accent': '245 158 11',
      '--border-radius-md': '8px',
      '--content-max-width': '1280px',
    },
    layoutConfig: {
      headerType: 'type-a',
      footerType: 'standard',
      productCardStyle: 'grid',
      bannerStyle: 'slider',
      categoryNavStyle: 'topbar',
      showBrandFilter: true,
      showPriceFilter: true,
      showSizeFilter: false,
      showColorFilter: false,
      productsPerRow: { desktop: 4, tablet: 3, mobile: 2 },
      productsPerPage: 20,
    },
    features: ['reviews', 'wishlist'],
    isActive: true,
    order: 1,
  },
  shop: {
    id: 'shop',
    name: '쇼핑몰',
    nameEn: 'Shop',
    description: '전문 쇼핑몰에 최적화된 테마',
    cssVariables: {
      '--color-primary': '17 24 39',
      '--color-primary-light': '55 65 81',
      '--color-primary-dark': '0 0 0',
      '--color-secondary': '107 114 128',
      '--color-accent': '239 68 68',
      '--border-radius-md': '4px',
      '--content-max-width': '1400px',
    },
    layoutConfig: {
      headerType: 'type-a',
      footerType: 'expanded',
      productCardStyle: 'grid',
      bannerStyle: 'slider',
      categoryNavStyle: 'mega-menu',
      showBrandFilter: true,
      showPriceFilter: true,
      showSizeFilter: true,
      showColorFilter: true,
      productsPerRow: { desktop: 4, tablet: 3, mobile: 2 },
      productsPerPage: 24,
    },
    features: ['reviews', 'wishlist', 'compare', 'quickview', 'recently-viewed'],
    isActive: true,
    order: 2,
  },
  company: {
    id: 'company',
    name: '기업/브랜드',
    nameEn: 'Company',
    description: '기업 홈페이지 겸 쇼핑몰 테마',
    cssVariables: {
      '--color-primary': '30 64 175',
      '--color-primary-light': '59 130 246',
      '--color-primary-dark': '29 78 216',
      '--color-secondary': '71 85 105',
      '--color-accent': '234 179 8',
      '--border-radius-md': '6px',
      '--content-max-width': '1200px',
    },
    layoutConfig: {
      headerType: 'type-b',
      footerType: 'expanded',
      productCardStyle: 'grid',
      bannerStyle: 'hero',
      categoryNavStyle: 'topbar',
      showBrandFilter: false,
      showPriceFilter: true,
      showSizeFilter: false,
      showColorFilter: false,
      productsPerRow: { desktop: 3, tablet: 2, mobile: 2 },
      productsPerPage: 12,
    },
    features: ['reviews', 'wishlist'],
    isActive: true,
    order: 3,
  },
  restaurant: {
    id: 'restaurant',
    name: '음식점/배달',
    nameEn: 'Restaurant',
    description: '음식점 및 배달 서비스 특화 테마',
    cssVariables: {
      '--color-primary': '220 38 38',
      '--color-primary-light': '248 113 113',
      '--color-primary-dark': '185 28 28',
      '--color-secondary': '120 113 108',
      '--color-accent': '234 179 8',
      '--border-radius-md': '12px',
      '--content-max-width': '1024px',
    },
    layoutConfig: {
      headerType: 'type-c',
      footerType: 'minimal',
      productCardStyle: 'magazine',
      bannerStyle: 'hero',
      categoryNavStyle: 'topbar',
      showBrandFilter: false,
      showPriceFilter: true,
      showSizeFilter: false,
      showColorFilter: false,
      productsPerRow: { desktop: 3, tablet: 2, mobile: 1 },
      productsPerPage: 12,
    },
    features: ['reviews', 'recently-viewed'],
    isActive: true,
    order: 4,
  },
  service: {
    id: 'service',
    name: '서비스업',
    nameEn: 'Service',
    description: '서비스업 종합 테마',
    cssVariables: {
      '--color-primary': '16 185 129',
      '--color-primary-light': '52 211 153',
      '--color-primary-dark': '5 150 105',
      '--color-secondary': '100 116 139',
      '--color-accent': '99 102 241',
      '--border-radius-md': '10px',
      '--content-max-width': '1200px',
    },
    layoutConfig: {
      headerType: 'type-b',
      footerType: 'standard',
      productCardStyle: 'grid',
      bannerStyle: 'slider',
      categoryNavStyle: 'sidebar',
      showBrandFilter: false,
      showPriceFilter: true,
      showSizeFilter: false,
      showColorFilter: false,
      productsPerRow: { desktop: 3, tablet: 2, mobile: 2 },
      productsPerPage: 16,
    },
    features: ['reviews', 'wishlist'],
    isActive: true,
    order: 5,
  },
};

export function getThemeDefinition(themeId: string): ThemeDefinition | null {
  // 'default' 테마를 'basic'으로 매핑 (기존 데이터 호환)
  const resolvedId = themeId === 'default' ? 'basic' : themeId;
  return themes[resolvedId] || null;
}

export function getAllThemes(): ThemeDefinition[] {
  return Object.values(themes)
    .filter((t) => t.isActive)
    .sort((a, b) => a.order - b.order);
}
